# Generated by Django 2.1.3 on 2019-03-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_itemthubnail_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ItemThubnailTag',
        ),
    ]
